addons:
  chrome: stable

language: node_js
sudo: false

node_js:
  - '6'
  - '8'
  - '9'
  - '10'
  - '11'

before_install:
  - if [[ `node -v` = v6* ]]; then npm i -g npx; fi
  - npx --version

script:
  - node --version
  - npm --version
  - npx --version
  - npm run build
  - npm test

os:
  - linux
  - osx
